// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "pb_ex.pb.h"
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace pbex {

namespace {


}  // namespace


void protobuf_AssignDesc_pb_5fex_2eproto() {
  protobuf_AddDesc_pb_5fex_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "pb_ex.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_pb_5fex_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_pb_5fex_2eproto() {
}

void protobuf_AddDesc_pb_5fex_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fdescriptor_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013pb_ex.proto\022\004pbex\032 google/protobuf/des"
    "criptor.proto:5\n\nServerType\022\037.google.pro"
    "tobuf.ServiceOptions\030\300\204= \001(\t:0\n\005Magic\022\037."
    "google.protobuf.ServiceOptions\030\301\204= \001(\005:/"
    "\n\005CmdID\022\036.google.protobuf.MethodOptions\030"
    "\300\204= \002(\005:3\n\tOptString\022\036.google.protobuf.M"
    "ethodOptions\030\301\204= \001(\t:/\n\005Usage\022\036.google.p"
    "rotobuf.MethodOptions\030\302\204= \001(\t", 309);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "pb_ex.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::ServiceOptions::default_instance(),
    1000000, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::ServiceOptions::default_instance(),
    1000001, 5, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::MethodOptions::default_instance(),
    1000000, 5, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::MethodOptions::default_instance(),
    1000001, 9, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::MethodOptions::default_instance(),
    1000002, 9, false, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_pb_5fex_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_pb_5fex_2eproto {
  StaticDescriptorInitializer_pb_5fex_2eproto() {
    protobuf_AddDesc_pb_5fex_2eproto();
  }
} static_descriptor_initializer_pb_5fex_2eproto_;

const ::std::string ServerType_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  ServerType(kServerTypeFieldNumber, ServerType_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  Magic(kMagicFieldNumber, 0);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  CmdID(kCmdIDFieldNumber, 0);
const ::std::string OptString_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  OptString(kOptStringFieldNumber, OptString_default);
const ::std::string Usage_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  Usage(kUsageFieldNumber, Usage_default);

// @@protoc_insertion_point(namespace_scope)

}  // namespace pbex

// @@protoc_insertion_point(global_scope)
