#!/bin/bash

if [ $# -lt 1 ]
then
    echo "Usage: `basename $0` <IP|HOSTNAME>"
    exit 1
fi

SVR_LST="$HOME/etc/appsvr.lst"

Uuser=$(grep -w "$1" $SVR_LST | awk '{print $3}')
echo $Uuser

#运行SVR_LST文件设置IP
. $SVR_LST

if [ "`echo $1|grep ^10.`" == "" ]
then
    hn=$1
    eval ip=\$${hn}
    echo $ip
fi

`ssh $hn@$ip`
